kind: pipeline
name: default
type: kubernetes

steps:
- name: tag
  image: alpine:latest
  commands:
    - echo -n $DRONE_BRANCH, $DRONE_COMMIT_SHA > .tags
    - if [ $DRONE_BRANCH == "master" ]; then echo -n ", lastest, stable" >> .tags ;fi

- name: build
  image: plugins/docker:latest
  settings:
    repo: j33r/php-fpm
    dockerfile: Dockerfile
    username: j33r
    password:
      from_secret: DOCKER_HUB_TOKEN
  when:
    event:
      exclude:
        - pull_request

- name: test
  image: plugins/docker:latest
  settings:
    repo: j33r/php-fpm
    tags: latest
    dockerfile: Dockerfile
    username: j33r
    password:
      from_secret: DOCKER_HUB_TOKEN
    dry_run: true
  when:
    event:
      - pull_request
